### ISSUE TITLE
error running package

### ISSUE THREAD

**Issue by redoxmatlab** [paruch-group/xrdtools#4]
Hi,

I am having problem running xrdtools. Anaconda 2.7 is up to date and all dependancies are installed. Could you please help resolving the error below:

$ xrdml calcite.xrdml
TTraceback (most recent call last):
  File "/Users/lortz/Anaconda/Anaconda2/anaconda/bin/xrdml", line 11, in <module>
    sys.exit(xrdml())
  File "/Users/lortz/Anaconda/Anaconda2/anaconda/lib/python2.7/site-packages/xrdtools/tools/clt.py", line 28, in xrdml
    data = xrdtools.read_xrdml(filename)
  File "/Users/lortz/Anaconda/Anaconda2/anaconda/lib/python2.7/site-packages/xrdtools/io.py", line 352, in read_xrdml
    data = _append2arr(data, scan, key)
  File "/Users/lortz/Anaconda/Anaconda2/anaconda/lib/python2.7/site-packages/xrdtools/io.py", line 159, in _append2arr
    data[key] = scan[key]
KeyError: u'Psi'

**Comment by bziegler** [comment]
Thanks for the solution. I implemented it and it's tested with python 2.7, 3.5 and 3.6 in the xrdtools-dev-0.1.1 branch. Feel free to test it.
