### ISSUE TITLE
Can't run command line "xrdml"

### ISSUE THREAD

**Issue by AinomN** [paruch-group/xrdtools#6]
I can run everthing fine if I do it trough a scrips. However, I am unable to use the linecommands.

>>> xrdml test_scan.xrdml
Traceback (most recent call last):
  File "/usr/local/bin/xrdml", line 11, in <module>
    sys.exit(xrdml())
  File "/usr/local/lib/python3.6/site-packages/xrdtools/tools/clt.py", line 50, in xrdml
    delimiter = args.delimiter.decode('string-escape')
AttributeError: 'str' object has no attribute 'decode'

**Comment by ghost** [comment]
Please try with the version 0.1.1 which is on pypi now.

**Comment by AinomN** [comment]
No, even with the new version I still get the following error when running in commandline:

>>>xrdml test_scan.xrdml
Traceback (most recent call last):
  File "/usr/local/bin/xrdml", line 11, in <module>
    sys.exit(xrdml())
  File "/usr/local/lib/python3.6/site-packages/xrdtools/tools/clt.py", line 59, in xrdml
    delimiter = args.delimiter.decode('string-escape')
AttributeError: 'str' object has no attribute 'decode'

When trying to run a python script with an .xrdml file, I now also get the following errer:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/xrdtools/io.py", line 309, in read_xrdml
    raise ValueError('The file is not conform with hte xrdml schema.')
ValueError: The file is not conform with hte xrdml schema.
[fe2o3.txt](https://github.com/paruch-group/xrdtools/files/1909626/fe2o3.txt)

**Comment by MShirazAhmad** [comment]
I am getting the following error
```
ValueError                                Traceback (most recent call last)
Cell In[1], line 3
      1 import xrdtools
----> 3 data = xrdtools.read_xrdml('TaB2.xrdml')

File ~/opt/anaconda3/envs/Xerus/lib/python3.8/site-packages/xrdtools/io.py:309, in read_xrdml(filename)
    307 valid = validate_xrdml_schema(filename)
    308 if valid is None:
--> 309     raise ValueError('The file is not conform with hte xrdml schema.')
    311 tree = etree.parse(os.path.join(path, filename)).getroot()
    312 # define the namespace

ValueError: The file is not conform with hte xrdml schema.
```

**Comment by Muthukamalan** [comment]
Hi @MShirazAhmad, I'm facing same issue, any suggestion to resolve this issue
